version: '3.1'
services:

  mongodb:
    image: mongo:5.0.3
    ports:
      - "27017:27017"

  animeapp:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb


