POST http://localhost:8081/api/anime/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhaG1lZEBnbWFpbC5jb20iLCJpYXQiOjE3NjEzNDA3MTYsImV4cCI6MTc2MTM0MjUxNn0.a-pBZ7pcy5Q0C1lYSV34yuPI2680Nu5ZJkXp6nDyC5c

{
    "name":"solo leveling II",
    "url":"www.w3anime.com"

}

###

GET http://localhost:8081/api/anime/all
Content-Type: application/json


###

DELETE http://localhost:8081/api/anime/delete/1
Content-Type: application/json